esphome:
  name: atx_controller
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Atx Controller Fallback Hotspot"
    password: "V5Jlex6EEwK7"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: adc
    pin: A0
    unit_of_measurement: "°C"
    name: "temperature ATX"
    update_interval: 60s
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT
    name: "switch atx controller"
    id: interrupteur
    filters:
      - delayed_on: 200ms
      - delayed_off: 200ms
    on_press:
      then:
        - switch.toggle: atx_switch
        
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT
    name: "atx state"
    id: state



switch:
  - platform: gpio
    pin: GPIO14
    inverted: true
    id: atx_switch
    name: "atx_switch"

