esphome:
  name: door01
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "42b9308206d6ba91eef43b8b20e28238"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Door01 Fallback Hotspot"
    password: "k1OX16voQNFH"

captive_portal:

switch:
  - platform: gpio
    pin: GPIO0
    id: bouton_ouverture_porte
    restore_mode: ALWAYS_ON
  - platform: template
    name: "bouton porte buisset"
    turn_on_action:
    - switch.turn_off: bouton_ouverture_porte
    - delay: 5000ms
    - switch.turn_on: bouton_ouverture_porte
  