esphome:
  name: door1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Door1 Fallback Hotspot"
    password: "FAiv2HOsO8Zq"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a
  
# Example configuration entry
sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: 600s

binary_sensor:
  - platform: gpio
    device_class: motion
    pin:
      number: GPIO13
      mode: INPUT
    name: "door inside PIR"
    id: insidePIR

  - platform: gpio
    device_class: door
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
    name: "door magnet"
    id: doorMagnet