esphome:
  name: 12v_mosfet_2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "12V Mosfet 2 Fallback Hotspot"
    password: "EyA29phwst10"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT
    name: "Interrupteur LEDs Lit"
    id: interrupteur
    filters:
      - delayed_on: 200ms
      - delayed_off: 200ms
    on_press:
      then:
        - light.toggle: led_1
        
  - platform: status
    name: "statut LEDs Lit"

output:
  - platform: esp8266_pwm
    pin: GPIO0
    inverted: false
    id: output_component1   
    
light:
  - platform: monochromatic
    name: "Lampe LEDs Lit"
    id: led_1
    output: output_component1
    
