esphome:
  name: esp01-cct-1
  friendly_name: esp01-CCT-1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "GB+vhVqlvwmL6gJxNdT2GGSwjI5lQiuKunZUaMtpCIA="

ota:
  password: "bef0e6e113eae4b487f25404c20ee2c6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp01-Cct-1 Fallback Hotspot"
    password: "p9D4pmLrW4dY"

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT
    name: "touch led-pannel-controller-n03-chevet"
    id: interrupteur
    filters:
      - delayed_on: 200ms
      - delayed_off: 200ms
    on_press:
      then:
        - light.toggle: led_pannel_controller_n03_chevet

        
  - platform: status
    name: "statut led-pannel-controller-n03-chevet"

output:
  - platform: esp8266_pwm
    pin: GPIO0
    inverted: false
    id: output_component1
  - platform: esp8266_pwm
    pin: GPIO1
    inverted: false
    id: output_component2
    
# Example configuration entry
light:
  - platform: cwww
    id: led_pannel_controller_n03_chevet
    name: "led-pannel-controller-n03-chevet"
    cold_white: output_component1
    warm_white: output_component2
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    