esphome:
  name: esp8266-mac-mini
  friendly_name: ESP8266 mac mini

esp8266:
  board: esp01_1m

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid_2
  password: !secret wifi_password_2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-Mac-Mini"
    password: "teGxhuR25Z3I"

captive_portal:

api:
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - servo.write:
            id: servo_mac_mini_esp01
            level: !lambda 'return level / 100.0;'


output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: GPIO0
    frequency: 50 Hz

servo:
  - id: servo_mac_mini_esp01
    output: pwm_output


switch:
  - platform: template
    name: "detach servo_mac_mini_esp01"
    turn_on_action:
    - servo.detach: servo_mac_mini_esp01
  - platform: gpio
    pin: GPIO1
    id: arduinoProMicro
    restore_mode: ALWAYS_OFF
  - platform: template
    name: "arduinoProMicro"
    turn_on_action:
    - switch.turn_on: arduinoProMicro
    - delay: 200ms
    - switch.turn_off: arduinoProMicro


binary_sensor:
  - platform: gpio
    device_class: POWER
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
    name: "boutton servo mac mini"
    id: boutton_servo_mac_mini
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms