esphome:
  name: espcam-garduino-buisset
  friendly_name: espcam-garduino-buisset

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "NwKvl1KfDk09XAbgW0fVS4WAzWKSKy5MZODgN0xhLYU="

ota:
  password: "e4845a8a7c95a4d2365de9193df5a6b0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Espcam-Garduino-Buisset"
    password: "wbtbiVAI0GX6"

captive_portal:

esp32_camera:
  name: espcam1
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600
  jpeg_quality: 10
  vertical_flip: false
  horizontal_mirror: false
  
output:
   - platform: gpio
     pin: GPIO4
     id: gpio_4 

light:
  - platform: binary
    output: gpio_4
    name: camera light d0297c 
  
# Example configuration entry
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
  

    