esphome:
  name: garduino-basilic-buisset

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "pNxqiaZJOC4pgf6eWJqraqKVo20RgRTQPVJM8o9S8+g="

ota:
  password: "c0baa1ed4db3f13ee60273c9b146e0bc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garduino-Basilic-Buisset"
    password: "wLq6DYrSAqa9"

captive_portal:


i2c:
  sda: GPIO4
  scl: GPIO5
  scan: True
  id: bus_a
  
# Example configuration entry
sensor:
  - platform: adc
    pin: A0
    name: "Soil Moisture"
    update_interval: 10s
    unit_of_measurement: "%"
    filters:
    - median:
        window_size: 7
        send_every: 4
        send_first_at: 1
    - calibrate_linear:
        - 0.85 -> 0.00
        - 0.44 -> 100.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0

# sensor:
#   - platform: adc
#     pin: A0
#     filters:
#       - lambda: |-
#           if (x > 0.7) {
#             return 0;
#           } else if (x < 0.26) {
#             return 100;
#           } else {
#             return (0.7-x) / (0.7-0.26) * 100.0;
#           }
#     unit_of_measurement: "%"
#     name: "soil moisture sensor"
#     update_interval: 10s
  - platform: bme280
    temperature:
      name: "BME280 Temperature Basilic"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure Basilic"
    humidity:
      name: "BME280 Humidity Basilic"
    address: 0x76
    update_interval: 60s
    
# Example configuration entry
switch:
  - platform: gpio
    pin: 14
    id: mosfet
    name: "pompe basilic"
    icon: "mdi:watering-can-outline"