esphome:
  name: garduino-v2023-05
  friendly_name: garduino-v2023-05

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "6kGAD9jzrLY03jrgKR3mY5Aa9MBKplsE/DVphoBdJec="

ota:
  password: "5c46be613c775665a13bdf5083e966bc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garduino-V2023-05"
    password: "z8dPQzrRcCBX"

captive_portal:
    
sensor:
  - platform: adc
    pin: A0
    filters:
      - lambda: |-
          if (x > 0.7) {
            return 0;
          } else if (x < 0.26) {
            return 100;
          } else {
            return (0.7-x) / (0.7-0.26) * 100.0;
          }
    unit_of_measurement: "%"
    name: "garduino-v2023-05-ADC"
    update_interval: 600s

switch:
  - platform: gpio
    pin: GPIO4
    id: garduino_v2023_05_pompe
    name: "garduino-v2023-05-pompe"
    icon: "mdi:watering-can-outline"
  - platform: gpio
    pin: GPIO5
    id: garduino_v2023_05_LEDS
    name: "garduino-v2023-05-leds"
    icon: "mdi:led-strip-variant"