esphome:
  name: jardin1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Jardin1 Fallback Hotspot"
    password: "sxLt6UMxPJXc"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: adc
    pin: A0
    filters:
      - lambda: |-
          if (x > 0.7) {
            return 0;
          } else if (x < 0.26) {
            return 100;
          } else {
            return (0.7-x) / (0.7-0.26) * 100.0;
          }
    unit_of_measurement: "%"
    name: "soil moisture sensor"
    update_interval: 60s
    
switch:
  - platform: gpio
    pin: D1
    id: sensor1
    name: "capteur 1 actif"
    interlock: [sensor2]
    
  - platform: gpio
    pin: D2
    id: sensor2
    name: "capteur 2 actif"
    interlock: [sensor1]
    
  - platform: gpio
    pin: D6
    id: led1
    name: "led 1"
    
  - platform: gpio
    pin: D5
    id: led2
    name: "led 2"