esphome:
  name: leds_chambre
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Leds Chambre Fallback Hotspot"
    password: "zZUEKMWED8S3"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
    name: "Interrupteur LEDs lit"
    id: interrupteur
    filters:
      - delayed_on: 200ms
      - delayed_off: 200ms
    on_release:
      then:
        - light.toggle: led_1
        
  - platform: status
    name: "statut lampe LEDs lit"

output:
  - platform: gpio
    pin: GPIO0
    inverted: true
    id: relay_1   
    
light:
  - platform: binary
    name: "Lampe LEDs lit"
    id: led_1
    output: relay_1