esphome:
  name: lumieres_cuisines_sha
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lumieres Cuisines Sha"
    password: "EX1sjR9gRTQO"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT
    name: "Interrupteur lumieres cuisine"
    id: interrupteur
    filters:
      - delayed_on: 200ms
      - delayed_off: 200ms
    on_press:
      then:
        - light.toggle: led_1
        - delay: 500ms 
        - light.toggle: led_2
        
  - platform: status
    name: "statut lumieres cuisine"

output:
  - platform: esp8266_pwm
    pin: GPIO0
    inverted: false
    id: output_component1
  - platform: esp8266_pwm
    pin: GPIO1
    inverted: false
    id: output_component2
    
light:
  - platform: monochromatic
    name: "lumieres cuisine gauche"
    id: led_1
    output: output_component1
  - platform: monochromatic
    name: "lumieres cuisine droit"
    id: led_2
    output: output_component2