esphome:
  name: tableau-buisset

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Pz3yEZcwqn80Dwq415jKMBOUhKxhusIVOo56qXW4E+o="

ota:
  password: "f391f29f1c9a2fe1226b377711065f20"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tableau-Buisset Fallback Hotspot"
    password: "xV80YVJAxIp9"

captive_portal:
    

switch:
  - platform: gpio
    pin: D1
    id: relay_salon
    restore_mode: ALWAYS_OFF
  - platform: template
    name: "telerupteur s    lon"
    icon: "mdi:lightbulb"
    turn_on_action:
    - switch.turn_on: relay_salon
    - delay: 200ms
    - switch.turn_off: relay_salon

binary_sensor:
  - platform: gpio
    device_class: light
    pin:
      number: GPIO14
    name: "etat lumiere séjour"
    id: etat_lumiere_sejour
    filters:
      - invert
      - delayed_on: 500ms
      - delayed_off: 500ms
  - platform: status
    name: "Status capteur lumiere séjour"
    