esphome:
  name: weather-station-sha
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "efdbf48a5d5676297d87a80387aef451"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Weather-Station-Sha"
    password: "4AeF488nUUNT"

captive_portal:

binary_sensor:
  - platform: gpio
    device_class: moisture
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
    name: "pluviometre"
    id: pluviometre
    filters:
      - invert: