esphome:
  name: wemos_test
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemos Test Fallback Hotspot"
    password: "DpxJ63KLy2xR"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "Relay"
    pin: D1
    
# Example configuration entry
sensor:
  - platform: adc
    pin: A0
    unit_of_measurement: "%"
    name: "tension batterie raw"
    update_interval: 600s